ALTER TABLE app_users
ADD COLUMN IF NOT EXISTS first_name VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE app_users ALTER COLUMN first_name DROP DEFAULT;
ALTER TABLE app_users ALTER COLUMN last_name DROP DEFAULT;
